# Generated by Django 4.0.4 on 2022-05-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=100)),
                ('supertypes', models.CharField(max_length=100)),
                ('manavalue', models.IntegerField()),
                ('coloridentity', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=300)),
                ('power', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('flavor_text', models.CharField(max_length=10000)),
                ('scryfallid', models.CharField(max_length=1000)),
            ],
        ),
    ]
