# Generated by Django 4.0.4 on 2022-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='coloridentity',
            new_name='colorIdentity',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='manavalue',
            new_name='manaValue',
        ),
        migrations.RemoveField(
            model_name='card',
            name='flavor_text',
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='scryfallid',
            field=models.CharField(max_length=200),
        ),
    ]
