# Generated by Django 4.0.4 on 2022-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_coloridentity_card_coloridentity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='scryfallid',
            new_name='scryfallId',
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
