# Generated by Django 4.0.4 on 2022-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_scryfallid_card_scryfallid_alter_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='manaValue',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(blank=True),
        ),
    ]
