# Generated by Django 4.0.4 on 2022-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_manavalue_alter_card_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
